### PR TITLE
#5 "Preview Popup"

### LINKED ISSUE #5: Error after clicking "Preview Popup" button
"Preview Popup" button is added to all screens under _Downloads_ > _Settings_ > _Extensions_. However, it works only on _Add to Cart Popup_ page. On other pages, there is a log in console caused by broken Ajax call. Call is broken because it generates PHP Fatal error:

> Uncaught TypeError: Argument 1 passed to `Aventura\Edd\AddToCartPopup\Core\Popup::generatePreview()` must be of the type `array`, `null` given, called in `/app/public/wp-content/plugins/edd-add-to-cart-popup/includes/Aventura/Edd/AddToCartPopup/Core/Popup.php` on line 119 and defined in `/app/public/wp-content/plugins/edd-add-to-cart-popup/includes/Aventura/Edd/AddToCartPopup/Core/Popup.php`:101

### PR DESCRIPTION
**Pull request by LisaCee**
Fixes #5 

- Add additional check to see if the current page section is ACP
- Update spaces to tabs
- Fix Yoda condition

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
I don't know if it's my specific combination of extensions being installed or something different going on, but the problem I am encountering with this solution is that the Add to Cart Popup is loading as the default Extensions tab. So that means that `section` isn't set in `INPUT_GET` at all, and the preview button isn't showing.

The ways that I can think of fixing it for this scenario are all kind of a pain and I'm honestly left wondering why there needs to be a button in the admin menu bar at all, since it's only supposed to show on this specific extension's settings screen, and there is already a Preview button there. Having it in the admin bar just feels a bit extra to me.

What would you think of just removing the admin bar button completely? The text about its existence under the other preview button would also have to be removed.

**Comment by LisaCee** [comment]
> the problem I am encountering with this solution is that the Add to Cart Popup is loading as the default Extensions tab. So that means that `section` isn't set in `INPUT_GET` at all, and the preview button isn't showing.

Weird. Add to Cart Popup is loading as the default on mine, too (good catch) but I am still getting the preview button. 

I fully support removing the preview from the admin menu. It is an odd feature and one that's not intuitive to find ([link](https://github.com/easydigitaldownloads/edd-add-to-cart-popup/issues/5#issuecomment-879028328)). I'll push up the code and see what @ashleyfae thinks on Monday.

**Comment by LisaCee** [comment]
It looks like ACP is loaded as the first extension in `release/1.1.3`, too.

**Review by robincornett — COMMENTED** [review]
I'm not sure why, but even now I am getting the JS error when I click the main Preview button. It seems like `tinymce.get( id )` may return `null`, even when it's specifically on this settings screen. I tried breaking that JS up into two parts so it could have a condition and that seemed to fix?

```js
            if (optionElem.is('textarea')) {
				var tiny = tinymce.get( id );
				if ( tiny ) {
					value = tiny.getContent();
				}
            }
```
That may be masking a different issue but I'm not sure.

**Comment by ashleyfae** [comment]
> What would you think of just removing the admin bar button completely? The text about its existence under the other preview button would also have to be removed.

Yep I'm good with this. Seems like a pointless feature to me.

**Review by ashleyfae — APPROVED** [review]
The settings are loading in a dedicated tab for me (not the main area). :thinking: Anyway this is all working fine for me, though I'm also good with @robincornett 's suggestion above if that fixes the problem she's experiencing.

**Comment by LisaCee** [comment]
@robincornett I didn't get a JS error like you, so please let me know if this fixes it.

**Review by robincornett — APPROVED** [review]
Thanks, this is working for me now!

In my install, the settings are visually in their own tab, but the URL is `https://edd.local/wp-admin/edit.php?post_type=download&page=edd-settings&tab=extensions` ... because there is no `section` the original fix wasn't working for me.

**Pull request merged**
